name: old_trustworthy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_database: ^3.1.5
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  intl: ^0.16.1
  provider: ^4.1.2
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  shared_preferences: ^0.5.8
  #cloud_firestore: ^0.13.5  
  #flutter_auth_buttons: ^0.10.0
  #font_awesome_flutter: ^8.8.1
  #equatable: ^1.1.1   
  
  
  

dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/products/

  fonts:
    - family:  OldTrustworthyIcons
      fonts:
      - asset: assets/icons/OldTrustworthyIcons.ttf