/// Flutter icons OldTrustworthyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OldTrustworthyIcons
///      fonts:
///       - asset: fonts/OldTrustworthyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OldTrustworthyIcons {
  OldTrustworthyIcons._();

  static const _kFontFam = 'OldTrustworthyIcons';
  static const _kFontPkg = null;

  static const IconData carnes = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frutas = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData congelados = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData higiene_personal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lacteos_fiambres = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limpieza = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verduras = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
